### ISSUE TITLE
Cannot download the data

### ISSUE THREAD

**Issue by Ha0Tang** [uber-research/LaneGCN#15]
When I execute this command `python preprocess_data.py -m lanegcn`, I encountered the following problem:

Traceback (most recent call last):
  File "preprocess_data.py", line 21, in <module>
    from data import ArgoDataset as Dataset, from_numpy, ref_copy, collate_fn
  File "/home/ht1/LaneGCN/data.py", line 12, in <module>
    from argoverse.map_representation.map_api import ArgoverseMap
  File "/home/ht1/anaconda3/envs/lanegcn/lib/python3.7/site-packages/argoverse/map_representation/map_api.py", line 21, in <module>
    from argoverse.utils.cv2_plotting_utils import get_img_contours
  File "/home/ht1/anaconda3/envs/lanegcn/lib/python3.7/site-packages/argoverse/utils/cv2_plotting_utils.py", line 9, in <module>
    from .calibration import CameraConfig, proj_cam_to_uv
  File "/home/ht1/anaconda3/envs/lanegcn/lib/python3.7/site-packages/argoverse/utils/calibration.py", line 14, in <module>
    from argoverse.utils.camera_stats import (
  File "/home/ht1/anaconda3/envs/lanegcn/lib/python3.7/site-packages/argoverse/utils/camera_stats.py", line 8, in <module>
    from argoverse.sensor_dataset_config import ArgoverseConfig
  File "/home/ht1/anaconda3/envs/lanegcn/lib/python3.7/site-packages/argoverse/sensor_dataset_config.py", line 55, in <module>
    cfg = hydra.compose(config_name=f"{DATASET_NAME}.yaml")
  File "/home/ht1/anaconda3/envs/lanegcn/lib/python3.7/site-packages/hydra/compose.py", line 33, in compose
    with_log_configuration=False,
  File "/home/ht1/anaconda3/envs/lanegcn/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 550, in compose_config
    from_shell=from_shell,
  File "/home/ht1/anaconda3/envs/lanegcn/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 150, in load_configuration
    from_shell=from_shell,
  File "/home/ht1/anaconda3/envs/lanegcn/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 244, in _load_configuration_impl
    skip_missing=run_mode == RunMode.MULTIRUN,
  File "/home/ht1/anaconda3/envs/lanegcn/lib/python3.7/site-packages/hydra/_internal/defaults_list.py", line 724, in create_defaults_list
    skip_missing=skip_missing,
  File "/home/ht1/anaconda3/envs/lanegcn/lib/python3.7/site-packages/hydra/_internal/defaults_list.py", line 695, in _create_defaults_list
    skip_missing=skip_missing,
  File "/home/ht1/anaconda3/envs/lanegcn/lib/python3.7/site-packages/hydra/_internal/defaults_list.py", line 343, in _create_defaults_tree
    overrides=overrides,
  File "/home/ht1/anaconda3/envs/lanegcn/lib/python3.7/site-packages/hydra/_internal/defaults_list.py", line 420, in _create_defaults_tree_impl
    return _expand_virtual_root(repo, root, overrides, skip_missing)
  File "/home/ht1/anaconda3/envs/lanegcn/lib/python3.7/site-packages/hydra/_internal/defaults_list.py", line 268, in _expand_virtual_root
    overrides=overrides,
  File "/home/ht1/anaconda3/envs/lanegcn/lib/python3.7/site-packages/hydra/_internal/defaults_list.py", line 427, in _create_defaults_tree_impl
    config_not_found_error(repo=repo, tree=root)
  File "/home/ht1/anaconda3/envs/lanegcn/lib/python3.7/site-packages/hydra/_internal/defaults_list.py", line 776, in config_not_found_error
    options=options,
hydra.errors.MissingConfigException: Cannot find primary config 'argoverse-v1.1.yaml'. Check that it's in your config search path.

Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=pkg://argoverse.config
        provider=schema, path=structured://

**Comment by Ha0Tang** [comment]
fixed
