### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tiansiyuan** [uber-research/LaneGCN#39]
python test.py -m lanegcn --weight=/home/jovyan/LaneGCN/36.000.ckpt --split=test

0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/jovyan/LaneGCN/test.py", line 118, in <module>
    main()
  File "/home/jovyan/LaneGCN/test.py", line 82, in main
    for ii, data in tqdm(enumerate(data_loader)):
  File "/home/venv/lib/python3.9/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 678, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/venv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/venv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jovyan/LaneGCN/data.py", line 384, in __getitem__
    data['argo_id'] = int(self.avl.seq_list[idx].name[:-4]) #160547
IndexError: list index out of range

**Comment by huanmanlou** [comment]
have you already solve that problem?I meet the similar question

**Comment by tiansiyuan** [comment]
> have you already solve that problem?I meet the similar question

Nope
